appenders:
  default:
    kind: console
    encoder:
      kind: pattern
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)(utc)} - {l}: {m}{n})}"
  log_file:
    kind: rolling_file
    append: true
    path: "logs/chita-bot.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} - {h({l})}: {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        base: 1
        count: 100
        pattern: "logs/chita-bot{}.log"

root:
  level: info
  appenders:
    - default
    - log_file